name: Api Deployment

on:
    push:
    workflow_dispatch:
        inputs:
            app:
                description: "Branch Name"
                required: false
                default: "main"

# Build the image, pust it to Docker Hub, and deploy it to the cluster
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # - uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/fast-template:latest
                  context: "{{defaultContext}}:backend"

            - name: Deploy
              # Only run this step if the branch is main
              #lif: github.ref == 'refs/heads/main'
              env:
                deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: |
                echo "Branch Name: ${{ github.ref }}"
                echo "Deploying.........."
                curl "$deploy_url"
